version: 2

updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "05:37"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 3

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "05:47"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 3
